### PR TITLE
Anchor fixes for r with dot below and amacron in Serif-Italic, added raised modifier I, ŋ, ɨ, ɛ, ʉ

### PR DESCRIPTION
**Pull request by kopeckyf**
These commits have hotfixes for two anchoring issues in LibertinusSerif-Italic:

- move the dot in `uni1e5b`, r with dot below, so that the dot is continuous with the r's body
- in `uni0101`, a with macron, add the `above` anchor so that ā can be stacked

The following glyphs are added in (at least some of) LibertinusSerif-Regular, -Italic, -Semibold, -SemiboldItalic, -Bold. They are not added in LibertinusSeminbold-Italic, because the glyphs that they are based on are largely missing there. 

- `uni1d35`, raised capital I
- `uni1d51`, raised small ŋ
- `uni1d4b`, raised small open e
- `uni1da4`, raised small i with stroke
- `uni1db6`, raised small u with bar

------

The files have been normalized and compiled without error. 
Btw, the italic variants show a strange behaviour when opened with FontForge (20190801). I opened an [issue in the fontforge repository](https://github.com/fontforge/fontforge/issues/4098) for this.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Please run `make normalize` after each change.

**Comment by khaledhosny** [comment]
Please also use more descriptive commit messages, keeping the long descriptions in the PR only will make hem inaccessible for anyone checking the commit log in the future.

**Comment by khaledhosny** [comment]
(if you use a different branch than master on your fork for the PRs, I might be able to push minor fixes like these directly to your fork).

**Comment by kopeckyf** [comment]
> Please run `make normalize` after each change.

I thought I did, sorry for the troubles :(

> (if you use a different branch than master on your fork for the PRs, I might be able to push minor fixes like these directly to your fork).

Good idea, do you need some sort of permissions on that branch?

**Comment by waldyrious** [comment]
> Good idea, do you need some sort of permissions on that branch?

When you're creating a PR from a branch other than `master`, github will show a checkbox that you can mark to allow edits from maintainers, like this:

Screenshot 2020-01-17 at 17 52 24

**Comment by kopeckyf** [comment]
> > Good idea, do you need some sort of permissions on that branch?
> 
> When you're creating a PR from a branch other than `master`, github will show a checkbox that you can mark to allow edits from maintainers, like this:
> 
> Screenshot 2020-01-17 at 17 52 24

That's great, @khaledhosny I'll close this PR and send it from another branch if you don't mind.

**Comment by khaledhosny** [comment]
New PR is fine.

**Comment by khaledhosny** [comment]
@kopeckyf Are you still working on this? I want to make a new release and I’d rather have this change in.

**Comment by kopeckyf** [comment]
@khaledhosny yes, this is still ongoing. Sorry about the delay. I wrote to Github support about the bug that PRs from forks that belong to an organisation do not show the "allow maintainers to edit the PR" function. They have not responded yet. I'll create a new PR from a private fork in a few hours.

**Comment by khaledhosny** [comment]
I think you need to create a branch on your fork, PR from master branch don't show this option AFAIK.

**Comment by kopeckyf** [comment]
@khaledhosny Mh, in my case the feature is available when PR'ing from the master branch, but not when the repository is owned by an organisation, even if a non-master branch is used on that organisation-repo....very confusing.

Anyway, you'll receive a PR with edits activated in a matter of seconds.

**Pull request closed without merging**
