### PR TITLE
unten_punkt anchors for Latin lowercase j, l, and ezh, uppercase J, Ezh

### PR DESCRIPTION
**Pull request by kopeckyf**
This commit aims to solve #279

### CODE REVIEW

**Comment by khaledhosny** [comment]
Why did you added the tone marks, they are not requested in #279 (see #30 for why they were remove in the first place).

**Comment by khaledhosny** [comment]
I fixed and pushed the first commit. Please open one pull request for each kind of change for easier review.

**Comment by kopeckyf** [comment]
Sorry, the two commits got appended in error. Would you accept another pull request for the short equal sign, and would it still be acceptable to you to copy the tonal letters from DejaVu?

**Comment by khaledhosny** [comment]
Yes to both.

**Pull request closed without merging**
