### PR TITLE
Remove whitespace from end-of-line in various files; fix a small typo

### PR DESCRIPTION
**Pull request by waldyrious**
Note: Didn't add `[ci skip]` to the commit just to be sure the changes to the sfd files were not problematic.

### CODE REVIEW

**Comment by khaledhosny** [comment]
I believe the spaces in the SFD files will be re-added by FontForge, so if we want to do that then the normalizer will have to remove them.

**Comment by waldyrious** [comment]
Ok, I can give it a shot tonight or during the weekend.

**Comment by waldyrious** [comment]
@khaledhosny just tested a small change and indeed the whitespace gets added at the end of the `Copyright:` line, but not elsewhere. Upon further investigation, I realized that this has already been fixed in FontForge (https://github.com/fontforge/fontforge/pull/1658 and https://github.com/fontforge/fontforge/pull/2713). In particular, here's the [relevant code](https://github.com/fontforge/fontforge/blob/master@{2020-04-04}/fontforge/sfd.c#L2306-L2307).

So it seems the issue was the empty "Copyright:" line that already exists in the  sfd files. If I remove it, FontForge does not add it back, and therefore doesn't add the space at the end. So I added a new commit removing those lines.

**Comment by khaledhosny** [comment]
I ran:
```
for f in sources/*.sfd; do fontforge -lang=ff -c "Open('$f');Save('$f');"; done
make normalize
```

And some of the trailing spaces are back (plus some curios change is the keyboard file that is probably unrelated). So either these spaces sholud be kept or the normalizer should remove them.

**Comment by waldyrious** [comment]
Huh, interesting. I didn't test all the fonts, indeed. I'll try again with your command and will make the necessary adjustments.

**Comment by waldyrious** [comment]
For reference, the whitespace additions I get are:

```diff
diff --git i/sources/LibertinusMath-Regular.sfd w/sources/LibertinusMath-Regular.sfd
index ec29723..e10a23b 100644
--- i/sources/LibertinusMath-Regular.sfd
+++ w/sources/LibertinusMath-Regular.sfd
@@ -537,57 +537,57 @@ MATH:ScriptPercentScaleDown: 80
 MATH:ScriptScriptPercentScaleDown: 60
 MATH:DelimitedSubFormulaMinHeight: 1500
 MATH:DisplayOperatorMinHeight: 1250
-MATH:MathLeading: 150
-MATH:AxisHeight: 260
-MATH:AccentBaseHeight: 440
-MATH:FlattenedAccentBaseHeight: 640
-MATH:SubscriptShiftDown: 210
-MATH:SubscriptTopMax: 360
-MATH:SubscriptBaselineDropMin: 45
-MATH:SuperscriptShiftUp: 375
-MATH:SuperscriptShiftUpCramped: 310
-MATH:SuperscriptBottomMin: 120
-MATH:SuperscriptBaselineDropMax: 230
-MATH:SubSuperscriptGapMin: 150
-MATH:SuperscriptBottomMaxWithSubscript: 380
-MATH:SpaceAfterScript: 43
-MATH:UpperLimitGapMin: 150
-MATH:UpperLimitBaselineRiseMin: 250
-MATH:LowerLimitGapMin: 150
-MATH:LowerLimitBaselineDropMin: 620
-MATH:StackTopShiftUp: 470
-MATH:StackTopDisplayStyleShiftUp: 750
-MATH:StackBottomShiftDown: 380
-MATH:StackBottomDisplayStyleShiftDown: 700
-MATH:StackGapMin: 200
-MATH:StackDisplayStyleGapMin: 330
-MATH:StretchStackTopShiftUp: 800
-MATH:StretchStackBottomShiftDown: 600
-MATH:StretchStackGapAboveMin: 65
-MATH:StretchStackGapBelowMin: 65
-MATH:FractionNumeratorShiftUp: 480
-MATH:FractionNumeratorDisplayStyleShiftUp: 580
-MATH:FractionDenominatorShiftDown: 480
-MATH:FractionDenominatorDisplayStyleShiftDown: 700
-MATH:FractionNumeratorGapMin: 65
-MATH:FractionNumeratorDisplayStyleGapMin: 198
-MATH:FractionRuleThickness: 65
-MATH:FractionDenominatorGapMin: 65
-MATH:FractionDenominatorDisplayStyleGapMin: 198
-MATH:SkewedFractionHorizontalGap: 300
-MATH:SkewedFractionVerticalGap: 65
-MATH:OverbarVerticalGap: 120
-MATH:OverbarRuleThickness: 40
-MATH:OverbarExtraAscender: 40
-MATH:UnderbarVerticalGap: 120
-MATH:UnderbarRuleThickness: 40
-MATH:UnderbarExtraDescender: 40
-MATH:RadicalVerticalGap: 90
-MATH:RadicalDisplayStyleVerticalGap: 170
-MATH:RadicalRuleThickness: 40
-MATH:RadicalExtraAscender: 65
-MATH:RadicalKernBeforeDegree: 85
-MATH:RadicalKernAfterDegree: -380
+MATH:MathLeading: 150 
+MATH:AxisHeight: 260 
+MATH:AccentBaseHeight: 440 
+MATH:FlattenedAccentBaseHeight: 640 
+MATH:SubscriptShiftDown: 210 
+MATH:SubscriptTopMax: 360 
+MATH:SubscriptBaselineDropMin: 45 
+MATH:SuperscriptShiftUp: 375 
+MATH:SuperscriptShiftUpCramped: 310 
+MATH:SuperscriptBottomMin: 120 
+MATH:SuperscriptBaselineDropMax: 230 
+MATH:SubSuperscriptGapMin: 150 
+MATH:SuperscriptBottomMaxWithSubscript: 380 
+MATH:SpaceAfterScript: 43 
+MATH:UpperLimitGapMin: 150 
+MATH:UpperLimitBaselineRiseMin: 250 
+MATH:LowerLimitGapMin: 150 
+MATH:LowerLimitBaselineDropMin: 620 
+MATH:StackTopShiftUp: 470 
+MATH:StackTopDisplayStyleShiftUp: 750 
+MATH:StackBottomShiftDown: 380 
+MATH:StackBottomDisplayStyleShiftDown: 700 
+MATH:StackGapMin: 200 
+MATH:StackDisplayStyleGapMin: 330 
+MATH:StretchStackTopShiftUp: 800 
+MATH:StretchStackBottomShiftDown: 600 
+MATH:StretchStackGapAboveMin: 65 
+MATH:StretchStackGapBelowMin: 65 
+MATH:FractionNumeratorShiftUp: 480 
+MATH:FractionNumeratorDisplayStyleShiftUp: 580 
+MATH:FractionDenominatorShiftDown: 480 
+MATH:FractionDenominatorDisplayStyleShiftDown: 700 
+MATH:FractionNumeratorGapMin: 65 
+MATH:FractionNumeratorDisplayStyleGapMin: 198 
+MATH:FractionRuleThickness: 65 
+MATH:FractionDenominatorGapMin: 65 
+MATH:FractionDenominatorDisplayStyleGapMin: 198 
+MATH:SkewedFractionHorizontalGap: 300 
+MATH:SkewedFractionVerticalGap: 65 
+MATH:OverbarVerticalGap: 120 
+MATH:OverbarRuleThickness: 40 
+MATH:OverbarExtraAscender: 40 
+MATH:UnderbarVerticalGap: 120 
+MATH:UnderbarRuleThickness: 40 
+MATH:UnderbarExtraDescender: 40 
+MATH:RadicalVerticalGap: 90 
+MATH:RadicalDisplayStyleVerticalGap: 170 
+MATH:RadicalRuleThickness: 40 
+MATH:RadicalExtraAscender: 65 
+MATH:RadicalKernBeforeDegree: 85 
+MATH:RadicalKernAfterDegree: -380 
 MATH:RadicalDegreeBottomRaisePercent: 50
 MATH:MinConnectorOverlap: 100
 Encoding: UnicodeFull
diff --git i/sources/LibertinusSans-Regular.sfd w/sources/LibertinusSans-Regular.sfd
index 77fc632..d5aa499 100644
--- i/sources/LibertinusSans-Regular.sfd
+++ w/sources/LibertinusSans-Regular.sfd
@@ -97,7 +97,7 @@ KernClass2: 9 4 "'kern' Cyrillic Kerning"
  39 uni040E uni0423 uni04EE uni04F0 uni04F2
  39 uni040C uni0416 uni041A uni0425 uni04DC
  15 uni041E uni042E
- 0
+ 0 
  31 uni0436 uni043A uni045C uni04DD
  47 uni0435 uni043E uni0440 uni0451 uni04E7 uni04E9
  15 uni042A uni042C
```

Those are exactly the spaces that are being removed in this PR (in sfd files). It would be nice to figure out if this could be solved on the fontforge side, but in the meantime, I'll edit the normalization script to remove them.

**Comment by waldyrious** [comment]
I pushed a simple change to the normalization script, that removes these changes (I also rebased the branch).

**Comment by waldyrious** [comment]
Regarding FontForge's introduction of these spaces, could [this line](https://github.com/fontforge/fontforge/blob/master@%7B2020-04-04%7D/fontforge/sfd.c#L2784) be the culprit?

**Comment by khaledhosny** [comment]
> Regarding FontForge's introduction of these spaces in the math and sans fonts, could [this line](https://github.com/fontforge/fontforge/blob/master@%7B2020-04-04%7D/fontforge/sfd.c#L2784) and [this one](https://github.com/fontforge/fontforge/blob/master@%7B2020-04-04%7D/fontforge/sfd.c#L2540), respectively, be the culprits for the issues?

Possibly.

>  I'm afraid then can't be simply removed outright, but if I'm in the right ballpark, I could at least propose a fix as an issue or a PR upstream.

That is not a requirement for me, as long as the normalizer handles it I’m fine. I no longer wish to touch FontForge code myself. If it weren’t for allowing others to contribute, I’d have moved to another much easier to use font editor already.

**Pull request merged**
