### PR TITLE
Fix metrics for Serbian alternative of U+0431

### PR DESCRIPTION
**Pull request by typiconman**
This fixes the error in metrics for uni0431.ital.

Sorry, I didn't generate the binaries. I tried to do this, but I get an error:

```
      BUILD  LibertinusSerif-Semibold
        OTL  LibertinusSerif-Semibold
       HINT  LibertinusSerif-Semibold
Option Error: All options must preceed the input font path <-o>.
Makefile:74: recipe for target 'build/LibertinusSerif-Semibold.hint.otf' failed
make: *** [build/LibertinusSerif-Semibold.hint.otf] Error 1
```

### CODE REVIEW

**Comment by khaledhosny** [comment]
Please run `make normalize`, you may also need to install the exact versions of the dependencies using the `requirements.txt` file to get the build to work.

**Comment by khaledhosny** [comment]
I took the liberty to fix and push your commit. Thanks for your contribution.

**Comment by typiconman** [comment]
Thanks. BTW, I still get `Option Error: All options must preceed the input font path <-o>.` when I run make. Not sure what is causing this.

**Comment by khaledhosny** [comment]
No idea, I thought the latest psautohint caused this, but I updated it and didn’t get the error.

**Comment by typiconman** [comment]
Well, this problem went away after I rebuilt psautohint from source. But now I get a different error message:

```
draw: unknown option -q
mudraw version 1.12.0
Usage: mudraw [options] file [pages]
	-p -	password

	-o -	output file name (%d for page number)
	-F -	output format (default inferred from output file name)
		raster: png, tga, pnm, pam, pbm, pkm, pwg, pcl, ps
		vector: svg, pdf, trace
		text: txt, html, stext

	-s -	show extra information:
		m - show memory use
		t - show timings
		f - show page features
		5 - show md5 checksum of rendered image

	-R -	rotate clockwise (default: 0 degrees)
	-r -	resolution in dpi (default: 72)
	-w -	width (in pixels) (maximum width if -r is specified)
	-h -	height (in pixels) (maximum height if -r is specified)
	-f -	fit width and/or height exactly; ignore original aspect ratio
	-B -	maximum band_height (pXm, pcl, pclm, ps, psd and png output only)
	-T -	number of threads to use for rendering (banded mode only)

	-W -	page width for EPUB layout
	-H -	page height for EPUB layout
	-S -	font size for EPUB layout
	-U -	file name of user stylesheet for EPUB layout
	-X	disable document styles for EPUB layout

	-c -	colorspace (mono, gray, grayalpha, rgb, rgba, cmyk, cmykalpha, filename of ICC profile)
	-e -	proof icc profile (filename of ICC profile)
	-G -	apply gamma correction
	-I	invert colors

	-A -	number of bits of antialiasing (0 to 8)
	-A -/-	number of bits of antialiasing (0 to 8) (graphics, text)
	-l -	minimum stroked line width (in pixels)
	-D	disable use of display list
	-i	ignore errors
	-L	low memory mode (avoid caching, clear objects after each page)
	-P	parallel interpretation/rendering
	-N	disable ICC workflow ("N"o color management)
	-O -	Control spot/overprint rendering
		 0 = No spot rendering
		 0 = No spot rendering
		 1 = Overprint simulation (default)
		 2 = Full spot rendering

	-y l	List the layer configs to stderr
	-y -	Select layer config (by number)
	-y -{,-}*	Select layer config (by number), and toggle the listed entries

	pages	comma separated list of page numbers and ranges
Makefile:139: recipe for target 'documentation/preview.svg' failed
make: *** [documentation/preview.svg] Error 1
```

**Comment by khaledhosny** [comment]
Use `make otf` to build the fonts only.

**Pull request merged**
